keywords: Hexo,HTML,Ben,CSS,安卓,android,Linux,linuxdeepin
author: Tom Wu,tom76kimo@gmail.com
description: 程式、信仰、人生
avatar: https://scontent-tpe1-1.xx.fbcdn.net/v/t1.0-9/12341397_10153448023623051_491318604065155247_n.jpg?oh=6de077dd62e80d0a0aea5baa99979ace&oe=59896ABD

twitter: tom76kimo
rss: atom.xml
instagram: tom76kimo

# Comment
duoshuo:
disqus: tom76kimo

root: '/blog'
