keywords: Hexo,HTML,Ben,CSS,安卓,android,Linux,linuxdeepin
author: Tom Wu,tom76kimo@gmail.com
description: 程式、信仰、人生
avatar: https://www.gravatar.com/avatar/46d51fec35d177693b418e4466dea33a?s=180

twitter: tom76kimo
rss: atom.xml
instagram: tom76kimo
github: tom76kimo

# Comment
duoshuo:
disqus: tom76kimo

root: '/blog'

# Analytics
# google-analytics:
ga: UA-46674413-7
